theme: jekyll-theme-minimal
title: "Dmitry Tabakerov"
description: "I write texts, and sometimes compilers do not find errors in them ¯\\_(ツ)_/¯\nNew line\nAnother new line"
logo: https://tabakerov.name/assets/logo.png
